version: '3.7'


services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - redis-queue
      - redis-cache
      - mailcatcher
    env_file: .env

  postgres:
    image: postgres:13.2-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"

  redis-queue:
    image: redis:6.0.12-alpine
    ports:
      - 6379:6379
    volumes:
      - redis-queue-data:/data

  redis-cache:
    image: redis:6.0.12-alpine
    ports:
      - 6380:6379
    volumes:
      - redis-cache-data:/data

volumes:
  redis-queue-data:
  redis-cache-data:
  postgres-data:
